CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_first_name TEXT NOT NULL,
    user_last_name TEXT NOT NULL,
    user_email TEXT NOT NULL UNIQUE,
    user_token TEXT,
    user_password_digest TEXT NOT NULL,
    user_created_at TIMESTAMP 
);