CREATE TABLE venues (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    venue_name TEXT NOT NULL,
    venue_website TEXT,
    venue_price TEXT,
    venue_rating TEXT,
    venue_capacity TEXT,
    venue_pros TEXT[],
    venue_cons TEXT[],
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);