CREATE TABLE venues (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    venue_name TEXT NOT NULL,
    venue_website TEXT NOT NULL,
    venue_price TEXT NOT NULL,
    venue_rating TEXT NOT NULL,
    venue_capacity TEXT NOT NULL,
    venue_pros TEXT[] NOT NULL,
    venue_cons TEXT[] NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);