CREATE TABLE photographers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    photographer_name TEXT NOT NULL,
    photographer_website TEXT NOT NULL,
    photographer_price TEXT NOT NULL,
    photographer_rating TEXT NOT NULL,
    photographer_pros TEXT[] NOT NULL,
    photographer_cons TEXT[] NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);