CREATE TABLE photographers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    photographer_name TEXT NOT NULL,
    photographer_website TEXT,
    photographer_price TEXT,
    photographer_rating TEXT,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);