CREATE TABLE caterers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    caterer_name TEXT NOT NULL,
    caterer_website TEXT,
    caterer_price TEXT,
    caterer_type TEXT,
    caterer_rating TEXT,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);