CREATE TABLE caterers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    caterer_name TEXT NOT NULL,
    caterer_website TEXT NOT NULL,
    caterer_price TEXT NOT NULL,
    caterer_type TEXT NOT NULL,
    caterer_rating TEXT NOT NULL,
    caterer_pros TEXT[] NOT NULL,
    caterer_cons TEXT[] NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);