CREATE TABLE guests (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    guest_first_name TEXT NOT NULL,
    guest_last_name TEXT NOT NULL,
    guest_type TEXT NOT NULL,
    guest_plus_one TEXT NOT NULL,
    guest_address TEXT,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);