CREATE TABLE guests (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    guest_first_name TEXT NOT NULL,
    guest_last_name TEXT NOT NULL,
    guest_type TEXT NOT NULL,
    guest_plus_one BOOLEAN NOT NULL,
    guest_street VARCHAR(60),
    guest_city TEXT,
    guest_state TEXT,
    guest_zip INTEGER,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);