CREATE TABLE florists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    florist_name TEXT NOT NULL,
    florist_website TEXT NOT NULL,
    florist_price TEXT NOT NULL,
    florist_rating TEXT NOT NULL,
    florist_pros TEXT[] NOT NULL,
    florist_cons TEXT[] NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);